pool:
  vmImage: 'VS2017-Win2016'

trigger: 
 - master

variables:
  buildConfiguration: 'Release'
  majorVersion: 1
  minorVersion: 0
  patchVersion: 0

steps:
- task : DotNetCoreInstaller@0
  inputs: 
   packageType: 'sdk'
   version: 2.2.104

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DeleteFiles@1
  inputs:
    SourceFolder: $(Build.ArtifactStagingDirectory)
    Contents: '*.nupkg'

- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '4.9.3'
    checkLatest: true
  continueOnError: false

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: $(Build.SourcesDirectory)/src/**/*.csproj
    packDestination: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: byBuildNumber
    majorVersion: $(majorVersion)
    minorVersion: $(minorVersion)
    patchVersion: $(patchVersion)