pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Debug'
  majorVersion: 1
  minorVersion: 0
  patchVersion: 2

steps:
- task : DotNetCoreInstaller@0
  inputs: 
   packageType: 'sdk'
   version: 3.0.100-preview6-012264

- script: dotnet tool install --global --add-source https://nuget.hybrid-technologies-solutions.com/nuget HTS_Packer
  displayName: 'dotnet install HTS_Packer tool'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: 'docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up -d'

- script: dotnet build -c $(buildConfiguration) CQELight_CI.sln
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '$(Build.SourcesDirectory)/tests/**/*.csproj'
  continueOnError: true

- task: DeleteFiles@1
  inputs:
    SourceFolder: $(Build.ArtifactStagingDirectory)
    Contents: '*.nupkg'

- script: htspack -o $(Build.ArtifactStagingDirectory) -prev
  displayName: 'Launch HTS Pack tool'